const categoryImages = [
  'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f0?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80',
];

const productImages = [
  'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1495446815901-8732e29db7f4?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f0?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1608571424352-9261a1e1e7c6?auto=format&fit=crop&w=1200&q=80',
];

const categoryData = [
  {
    name: 'Electronics',
    description: 'Phones, laptops, audio gear, and everyday tech essentials',
    image: categoryImages[0],
  },
  {
    name: 'Clothing',
    description: 'Stylish apparel for work, leisure, and travel',
    image: categoryImages[1],
  },
  {
    name: 'Home & Kitchen',
    description: 'Cookware, decor, and useful upgrades for modern homes',
    image: categoryImages[2],
  },
  {
    name: 'Books',
    description: 'Best-selling books, guides, and inspiring reads',
    image: categoryImages[3],
  },
  {
    name: 'Sports & Outdoors',
    description: 'Gear for fitness, adventure, and active living',
    image: categoryImages[4],
  },
  {
    name: 'Beauty & Wellness',
    description: 'Care essentials for skin, self-care, and wellbeing',
    image: categoryImages[5],
  },
];

const productData = (categories, adminId) => {
  const findCategoryId = (name) => categories.find((category) => category.name === name)?._id || categories[0]._id;

  return [
    {
      name: 'Wireless Headphones',
      category: findCategoryId('Electronics'),
      price: 2499,
      stock: 50,
      brand: 'SoundWave',
      ratingsAverage: 4.6,
      ratingsCount: 182,
      images: [productImages[0]],
      description:
        'Active noise cancellation, soft over-ear cushions, and all-day battery life for immersive listening.',
      createdBy: adminId,
    },
    {
      name: 'Smartphone X12',
      category: findCategoryId('Electronics'),
      price: 24999,
      stock: 20,
      brand: 'TechCo',
      ratingsAverage: 4.5,
      ratingsCount: 230,
      images: [productImages[1]],
      description:
        'Sleek display, responsive camera, and fast charging for everything you need on the go.',
      createdBy: adminId,
    },
    {
      name: 'Ultrabook Pro 14',
      category: findCategoryId('Electronics'),
      price: 79999,
      stock: 15,
      brand: 'PixelStone',
      ratingsAverage: 4.7,
      ratingsCount: 94,
      images: [productImages[2]],
      description:
        'A lightweight laptop for creative work, multitasking, and standout performance.',
      createdBy: adminId,
    },
    {
      name: 'AeroFit Smartwatch',
      category: findCategoryId('Electronics'),
      price: 6999,
      stock: 38,
      brand: 'AeroFit',
      ratingsAverage: 4.4,
      ratingsCount: 121,
      images: [productImages[3]],
      description:
        'Track fitness, notifications, and sleep insights with a bright always-on display.',
      createdBy: adminId,
    },
    {
      name: 'Portable Bluetooth Speaker',
      category: findCategoryId('Electronics'),
      price: 3299,
      stock: 44,
      brand: 'EchoBeat',
      ratingsAverage: 4.5,
      ratingsCount: 167,
      images: [productImages[4]],
      description:
        'Room-filling sound, durable design, and long battery life for indoor and outdoor listening.',
      createdBy: adminId,
    },
    {
      name: 'Cotton T-Shirt',
      category: findCategoryId('Clothing'),
      price: 499,
      stock: 100,
      brand: 'UrbanWear',
      ratingsAverage: 4.3,
      ratingsCount: 112,
      images: [productImages[5]],
      description: 'Breathable cotton, modern fit, and easy layering for day-to-day comfort.',
      createdBy: adminId,
    },
    {
      name: 'Denim Jacket',
      category: findCategoryId('Clothing'),
      price: 1999,
      stock: 40,
      brand: 'UrbanWear',
      ratingsAverage: 4.5,
      ratingsCount: 78,
      images: [productImages[6]],
      description: 'Durable denim with a classic cut, perfect for layering across seasons.',
      createdBy: adminId,
    },
    {
      name: 'Premium Linen Shirt',
      category: findCategoryId('Clothing'),
      price: 1799,
      stock: 52,
      brand: 'North Thread',
      ratingsAverage: 4.4,
      ratingsCount: 85,
      images: [productImages[7]],
      description:
        'A breathable tailored shirt with a polished look that works from office to weekend.',
      createdBy: adminId,
    },
    {
      name: 'Everyday Cargo Joggers',
      category: findCategoryId('Clothing'),
      price: 1499,
      stock: 61,
      brand: 'MotionLab',
      ratingsAverage: 4.3,
      ratingsCount: 72,
      images: [productImages[8]],
      description:
        'Relaxed comfort, stretch fabric, and utility pockets for all-day versatility.',
      createdBy: adminId,
    },
    {
      name: 'Classic Leather Backpack',
      category: findCategoryId('Clothing'),
      price: 2799,
      stock: 29,
      brand: 'Carry House',
      ratingsAverage: 4.6,
      ratingsCount: 109,
      images: [productImages[9]],
      description:
        'A refined backpack with laptop storage, travel-ready comfort, and timeless styling.',
      createdBy: adminId,
    },
    {
      name: 'Non-Stick Pan Set',
      category: findCategoryId('Home & Kitchen'),
      price: 1299,
      stock: 30,
      brand: 'HomeChef',
      ratingsAverage: 4.2,
      ratingsCount: 53,
      images: [productImages[10]],
      description: 'A versatile set for every kitchen, with easy cleanup and durable coating.',
      createdBy: adminId,
    },
    {
      name: 'Study Table Lamp',
      category: findCategoryId('Home & Kitchen'),
      price: 899,
      stock: 60,
      brand: 'BrightLite',
      ratingsAverage: 4.3,
      ratingsCount: 67,
      images: [productImages[11]],
      description: 'Warm light, adjustable neck, and sturdy design for every workspace.',
      createdBy: adminId,
    },
    {
      name: 'Air Fryer Oven XL',
      category: findCategoryId('Home & Kitchen'),
      price: 8499,
      stock: 18,
      brand: 'KitchenNova',
      ratingsAverage: 4.7,
      ratingsCount: 143,
      images: [productImages[12]],
      description:
        'Bake, roast, crisp, and reheat with one countertop appliance built for family meals.',
      createdBy: adminId,
    },
    {
      name: 'Minimal Ceramic Dinner Set',
      category: findCategoryId('Home & Kitchen'),
      price: 2199,
      stock: 33,
      brand: 'Casa Form',
      ratingsAverage: 4.5,
      ratingsCount: 88,
      images: [productImages[13]],
      description:
        'Elegant matte-finish plates and bowls that elevate both everyday meals and hosting.',
      createdBy: adminId,
    },
    {
      name: 'Aroma Diffuser Set',
      category: findCategoryId('Home & Kitchen'),
      price: 1499,
      stock: 48,
      brand: 'CalmNest',
      ratingsAverage: 4.4,
      ratingsCount: 91,
      images: [productImages[14]],
      description:
        'Soft ambient mist and essential oil blends designed to make any room feel relaxing.',
      createdBy: adminId,
    },
    {
      name: 'The Pragmatic Programmer',
      category: findCategoryId('Books'),
      price: 799,
      stock: 25,
      brand: 'Pearson',
      ratingsAverage: 4.8,
      ratingsCount: 310,
      images: [productImages[15]],
      description: 'A software development classic for better design, testing, and career growth.',
      createdBy: adminId,
    },
    {
      name: 'Atomic Habits',
      category: findCategoryId('Books'),
      price: 399,
      stock: 80,
      brand: 'Penguin',
      ratingsAverage: 4.7,
      ratingsCount: 520,
      images: [productImages[16]],
      description: 'Proven strategies to build better routines and make small changes stick.',
      createdBy: adminId,
    },
    {
      name: 'Deep Work',
      category: findCategoryId('Books'),
      price: 499,
      stock: 46,
      brand: 'Grand Central',
      ratingsAverage: 4.6,
      ratingsCount: 188,
      images: [productImages[17]],
      description:
        'A practical guide to focused work, better concentration, and meaningful productivity.',
      createdBy: adminId,
    },
    {
      name: 'Mindset Mastery Journal',
      category: findCategoryId('Books'),
      price: 699,
      stock: 57,
      brand: 'Paper Peak',
      ratingsAverage: 4.5,
      ratingsCount: 64,
      images: [productImages[18]],
      description:
        'A guided journal filled with prompts for reflection, growth planning, and daily clarity.',
      createdBy: adminId,
    },
    {
      name: 'Running Sneakers',
      category: findCategoryId('Sports & Outdoors'),
      price: 3499,
      stock: 25,
      brand: 'Sprint',
      ratingsAverage: 4.4,
      ratingsCount: 146,
      images: [productImages[19]],
      description: 'Responsive cushioning, traction grip, and comfort for daily runs and gym sessions.',
      createdBy: adminId,
    },
    {
      name: 'Yoga Mat Pro',
      category: findCategoryId('Sports & Outdoors'),
      price: 1299,
      stock: 74,
      brand: 'FlexForm',
      ratingsAverage: 4.5,
      ratingsCount: 133,
      images: [productImages[20]],
      description:
        'A thick anti-slip mat designed for yoga, stretching, and home workout stability.',
      createdBy: adminId,
    },
    {
      name: 'Trail Hydration Bottle',
      category: findCategoryId('Sports & Outdoors'),
      price: 899,
      stock: 63,
      brand: 'PeakTrail',
      ratingsAverage: 4.3,
      ratingsCount: 76,
      images: [productImages[21]],
      description:
        'Leakproof stainless steel bottle that keeps drinks cold during commutes, hikes, and workouts.',
      createdBy: adminId,
    },
    {
      name: 'Compact Camping Tent',
      category: findCategoryId('Sports & Outdoors'),
      price: 4999,
      stock: 17,
      brand: 'WildHarbor',
      ratingsAverage: 4.6,
      ratingsCount: 58,
      images: [productImages[22]],
      description:
        'Lightweight, weather-ready shelter built for weekend escapes and easy travel packing.',
      createdBy: adminId,
    },
    {
      name: 'Skincare Kit',
      category: findCategoryId('Beauty & Wellness'),
      price: 1299,
      stock: 55,
      brand: 'PureGlow',
      ratingsAverage: 4.5,
      ratingsCount: 98,
      images: [productImages[23]],
      description: 'Gentle essentials for healthy skin, including cleanser, toner, and moisturizer.',
      createdBy: adminId,
    },
    {
      name: 'Vitamin C Face Serum',
      category: findCategoryId('Beauty & Wellness'),
      price: 999,
      stock: 70,
      brand: 'Lumora',
      ratingsAverage: 4.4,
      ratingsCount: 154,
      images: [productImages[24]],
      description:
        'A brightening serum that helps support an even-looking tone and healthy glow.',
      createdBy: adminId,
    },
    {
      name: 'Spa Relaxation Gift Box',
      category: findCategoryId('Beauty & Wellness'),
      price: 1899,
      stock: 36,
      brand: 'Soul Ritual',
      ratingsAverage: 4.6,
      ratingsCount: 81,
      images: [productImages[25]],
      description:
        'A self-care set with bath salts, candles, and body care for stress-free evenings.',
      createdBy: adminId,
    },
    {
      name: 'Electric Toothbrush Duo',
      category: findCategoryId('Beauty & Wellness'),
      price: 2499,
      stock: 28,
      brand: 'SmileGrid',
      ratingsAverage: 4.5,
      ratingsCount: 97,
      images: [productImages[26]],
      description:
        'A two-brush set with timer modes and soft bristles for a cleaner, more comfortable routine.',
      createdBy: adminId,
    },
  ];
};

module.exports = { categoryData, productData };
