const placeholderCategoryImage = '/images/category-placeholder.svg';
const placeholderProductImage = '/images/product-placeholder.svg';

const categoryData = [
  {
    name: 'Electronics',
    description: 'Phones, laptops, audio gear, and everyday tech essentials',
    image: placeholderCategoryImage,
  },
  {
    name: 'Clothing',
    description: 'Stylish apparel for work, leisure, and travel',
    image: placeholderCategoryImage,
  },
  {
    name: 'Home & Kitchen',
    description: 'Cookware, decor, and useful upgrades for modern homes',
    image: placeholderCategoryImage,
  },
  {
    name: 'Books',
    description: 'Best-selling books, guides, and inspiring reads',
    image: placeholderCategoryImage,
  },
  {
    name: 'Sports & Outdoors',
    description: 'Gear for fitness, adventure, and active living',
    image: placeholderCategoryImage,
  },
  {
    name: 'Beauty & Wellness',
    description: 'Care essentials for skin, self-care, and wellbeing',
    image: placeholderCategoryImage,
  },
];

const productData = (categories, adminId) => {
  const findCategoryId = (name) => categories.find((category) => category.name === name)?._id || categories[0]._id;

  return [
    {
      name: 'Wireless Headphones',
      category: findCategoryId('Electronics'),
      price: 2499,
      stock: 50,
      brand: 'SoundWave',
      ratingsAverage: 4.6,
      ratingsCount: 182,
      images: [placeholderProductImage],
      description:
        'Active noise cancellation, soft over-ear cushions, and all-day battery life for immersive listening.',
      createdBy: adminId,
    },
    {
      name: 'Smartphone X12',
      category: findCategoryId('Electronics'),
      price: 24999,
      stock: 20,
      brand: 'TechCo',
      ratingsAverage: 4.5,
      ratingsCount: 230,
      images: [placeholderProductImage],
      description:
        'Sleek display, responsive camera, and fast charging for everything you need on the go.',
      createdBy: adminId,
    },
    {
      name: 'Ultrabook Pro 14',
      category: findCategoryId('Electronics'),
      price: 79999,
      stock: 15,
      brand: 'PixelStone',
      ratingsAverage: 4.7,
      ratingsCount: 94,
      images: [placeholderProductImage],
      description:
        'A lightweight laptop for creative work, multitasking, and standout performance.',
      createdBy: adminId,
    },
    {
      name: 'AeroFit Smartwatch',
      category: findCategoryId('Electronics'),
      price: 6999,
      stock: 38,
      brand: 'AeroFit',
      ratingsAverage: 4.4,
      ratingsCount: 121,
      images: [placeholderProductImage],
      description:
        'Track fitness, notifications, and sleep insights with a bright always-on display.',
      createdBy: adminId,
    },
    {
      name: 'Portable Bluetooth Speaker',
      category: findCategoryId('Electronics'),
      price: 3299,
      stock: 44,
      brand: 'EchoBeat',
      ratingsAverage: 4.5,
      ratingsCount: 167,
      images: [placeholderProductImage],
      description:
        'Room-filling sound, durable design, and long battery life for indoor and outdoor listening.',
      createdBy: adminId,
    },
    {
      name: 'Cotton T-Shirt',
      category: findCategoryId('Clothing'),
      price: 499,
      stock: 100,
      brand: 'UrbanWear',
      ratingsAverage: 4.3,
      ratingsCount: 112,
      images: [placeholderProductImage],
      description: 'Breathable cotton, modern fit, and easy layering for day-to-day comfort.',
      createdBy: adminId,
    },
    {
      name: 'Denim Jacket',
      category: findCategoryId('Clothing'),
      price: 1999,
      stock: 40,
      brand: 'UrbanWear',
      ratingsAverage: 4.5,
      ratingsCount: 78,
      images: [placeholderProductImage],
      description: 'Durable denim with a classic cut, perfect for layering across seasons.',
      createdBy: adminId,
    },
    {
      name: 'Premium Linen Shirt',
      category: findCategoryId('Clothing'),
      price: 1799,
      stock: 52,
      brand: 'North Thread',
      ratingsAverage: 4.4,
      ratingsCount: 85,
      images: [placeholderProductImage],
      description:
        'A breathable tailored shirt with a polished look that works from office to weekend.',
      createdBy: adminId,
    },
    {
      name: 'Everyday Cargo Joggers',
      category: findCategoryId('Clothing'),
      price: 1499,
      stock: 61,
      brand: 'MotionLab',
      ratingsAverage: 4.3,
      ratingsCount: 72,
      images: [placeholderProductImage],
      description:
        'Relaxed comfort, stretch fabric, and utility pockets for all-day versatility.',
      createdBy: adminId,
    },
    {
      name: 'Classic Leather Backpack',
      category: findCategoryId('Clothing'),
      price: 2799,
      stock: 29,
      brand: 'Carry House',
      ratingsAverage: 4.6,
      ratingsCount: 109,
      images: [placeholderProductImage],
      description:
        'A refined backpack with laptop storage, travel-ready comfort, and timeless styling.',
      createdBy: adminId,
    },
    {
      name: 'Non-Stick Pan Set',
      category: findCategoryId('Home & Kitchen'),
      price: 1299,
      stock: 30,
      brand: 'HomeChef',
      ratingsAverage: 4.2,
      ratingsCount: 53,
      images: [placeholderProductImage],
      description: 'A versatile set for every kitchen, with easy cleanup and durable coating.',
      createdBy: adminId,
    },
    {
      name: 'Study Table Lamp',
      category: findCategoryId('Home & Kitchen'),
      price: 899,
      stock: 60,
      brand: 'BrightLite',
      ratingsAverage: 4.3,
      ratingsCount: 67,
      images: [placeholderProductImage],
      description: 'Warm light, adjustable neck, and sturdy design for every workspace.',
      createdBy: adminId,
    },
    {
      name: 'Air Fryer Oven XL',
      category: findCategoryId('Home & Kitchen'),
      price: 8499,
      stock: 18,
      brand: 'KitchenNova',
      ratingsAverage: 4.7,
      ratingsCount: 143,
      images: [placeholderProductImage],
      description:
        'Bake, roast, crisp, and reheat with one countertop appliance built for family meals.',
      createdBy: adminId,
    },
    {
      name: 'Minimal Ceramic Dinner Set',
      category: findCategoryId('Home & Kitchen'),
      price: 2199,
      stock: 33,
      brand: 'Casa Form',
      ratingsAverage: 4.5,
      ratingsCount: 88,
      images: [placeholderProductImage],
      description:
        'Elegant matte-finish plates and bowls that elevate both everyday meals and hosting.',
      createdBy: adminId,
    },
    {
      name: 'Aroma Diffuser Set',
      category: findCategoryId('Home & Kitchen'),
      price: 1499,
      stock: 48,
      brand: 'CalmNest',
      ratingsAverage: 4.4,
      ratingsCount: 91,
      images: [placeholderProductImage],
      description:
        'Soft ambient mist and essential oil blends designed to make any room feel relaxing.',
      createdBy: adminId,
    },
    {
      name: 'The Pragmatic Programmer',
      category: findCategoryId('Books'),
      price: 799,
      stock: 25,
      brand: 'Pearson',
      ratingsAverage: 4.8,
      ratingsCount: 310,
      images: [placeholderProductImage],
      description: 'A software development classic for better design, testing, and career growth.',
      createdBy: adminId,
    },
    {
      name: 'Atomic Habits',
      category: findCategoryId('Books'),
      price: 399,
      stock: 80,
      brand: 'Penguin',
      ratingsAverage: 4.7,
      ratingsCount: 520,
      images: [placeholderProductImage],
      description: 'Proven strategies to build better routines and make small changes stick.',
      createdBy: adminId,
    },
    {
      name: 'Deep Work',
      category: findCategoryId('Books'),
      price: 499,
      stock: 46,
      brand: 'Grand Central',
      ratingsAverage: 4.6,
      ratingsCount: 188,
      images: [placeholderProductImage],
      description:
        'A practical guide to focused work, better concentration, and meaningful productivity.',
      createdBy: adminId,
    },
    {
      name: 'Mindset Mastery Journal',
      category: findCategoryId('Books'),
      price: 699,
      stock: 57,
      brand: 'Paper Peak',
      ratingsAverage: 4.5,
      ratingsCount: 64,
      images: [placeholderProductImage],
      description:
        'A guided journal filled with prompts for reflection, growth planning, and daily clarity.',
      createdBy: adminId,
    },
    {
      name: 'Running Sneakers',
      category: findCategoryId('Sports & Outdoors'),
      price: 3499,
      stock: 25,
      brand: 'Sprint',
      ratingsAverage: 4.4,
      ratingsCount: 146,
      images: [placeholderProductImage],
      description: 'Responsive cushioning, traction grip, and comfort for daily runs and gym sessions.',
      createdBy: adminId,
    },
    {
      name: 'Yoga Mat Pro',
      category: findCategoryId('Sports & Outdoors'),
      price: 1299,
      stock: 74,
      brand: 'FlexForm',
      ratingsAverage: 4.5,
      ratingsCount: 133,
      images: [placeholderProductImage],
      description:
        'A thick anti-slip mat designed for yoga, stretching, and home workout stability.',
      createdBy: adminId,
    },
    {
      name: 'Trail Hydration Bottle',
      category: findCategoryId('Sports & Outdoors'),
      price: 899,
      stock: 63,
      brand: 'PeakTrail',
      ratingsAverage: 4.3,
      ratingsCount: 76,
      images: [placeholderProductImage],
      description:
        'Leakproof stainless steel bottle that keeps drinks cold during commutes, hikes, and workouts.',
      createdBy: adminId,
    },
    {
      name: 'Compact Camping Tent',
      category: findCategoryId('Sports & Outdoors'),
      price: 4999,
      stock: 17,
      brand: 'WildHarbor',
      ratingsAverage: 4.6,
      ratingsCount: 58,
      images: [placeholderProductImage],
      description:
        'Lightweight, weather-ready shelter built for weekend escapes and easy travel packing.',
      createdBy: adminId,
    },
    {
      name: 'Skincare Kit',
      category: findCategoryId('Beauty & Wellness'),
      price: 1299,
      stock: 55,
      brand: 'PureGlow',
      ratingsAverage: 4.5,
      ratingsCount: 98,
      images: [placeholderProductImage],
      description: 'Gentle essentials for healthy skin, including cleanser, toner, and moisturizer.',
      createdBy: adminId,
    },
    {
      name: 'Vitamin C Face Serum',
      category: findCategoryId('Beauty & Wellness'),
      price: 999,
      stock: 70,
      brand: 'Lumora',
      ratingsAverage: 4.4,
      ratingsCount: 154,
      images: [placeholderProductImage],
      description:
        'A brightening serum that helps support an even-looking tone and healthy glow.',
      createdBy: adminId,
    },
    {
      name: 'Spa Relaxation Gift Box',
      category: findCategoryId('Beauty & Wellness'),
      price: 1899,
      stock: 36,
      brand: 'Soul Ritual',
      ratingsAverage: 4.6,
      ratingsCount: 81,
      images: [placeholderProductImage],
      description:
        'A self-care set with bath salts, candles, and body care for stress-free evenings.',
      createdBy: adminId,
    },
    {
      name: 'Electric Toothbrush Duo',
      category: findCategoryId('Beauty & Wellness'),
      price: 2499,
      stock: 28,
      brand: 'SmileGrid',
      ratingsAverage: 4.5,
      ratingsCount: 97,
      images: [placeholderProductImage],
      description:
        'A two-brush set with timer modes and soft bristles for a cleaner, more comfortable routine.',
      createdBy: adminId,
    },
  ];
};

module.exports = { categoryData, productData };
